<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>修改用户按钮</description>
   <name>btn_editUsers</name>
   <tag></tag>
   <elementGuidId>ec236d91-0aeb-46b0-a04b-0ea1ffbd4340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[normalize-space(.)='修改']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[normalize-space(.)='修改']</value>
   </webElementProperties>
</WebElementEntity>
