<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>导出按钮</description>
   <name>btn_outFile</name>
   <tag></tag>
   <elementGuidId>7f5da8af-3575-4724-9c91-9e407195a19e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[normalize-space(.)='导出']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[normalize-space(.)='导出']</value>
   </webElementProperties>
</WebElementEntity>
