<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>单一用户重置按钮</description>
   <name>btn_resetPw</name>
   <tag></tag>
   <elementGuidId>f779a0bc-2a74-4b76-b89a-aa6497c2d6f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[normalize-space(text())='test']/../td/a[normalize-space(.)='重置']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[normalize-space(text())='test']/../td/a[normalize-space(.)='重置']</value>
   </webElementProperties>
</WebElementEntity>
