<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>成功提示框</description>
   <name>mbox_succeed</name>
   <tag></tag>
   <elementGuidId>bac4b95a-338e-4bb3-b746-889c1002eda9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/div[normalize-space(.)='操作成功']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/div[normalize-space(.)='操作成功']</value>
   </webElementProperties>
</WebElementEntity>
