<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>选择用户状态项</description>
   <name>select_userStatus</name>
   <tag></tag>
   <elementGuidId>dc6e1b16-9f01-4c3c-ad33-2f5011629f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select/option[text()='正常']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select/option[text()='正常']</value>
   </webElementProperties>
</WebElementEntity>
