<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>岗位管理</description>
   <name>tbtn_postManage</name>
   <tag></tag>
   <elementGuidId>b744b94d-32d2-4e6a-8821-2c0b61b40250</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li/a[normalize-space(text())='岗位管理']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li/a[normalize-space(text())='岗位管理']</value>
   </webElementProperties>
</WebElementEntity>
