<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>参数管理</description>
   <name>tbtn_parameterSetting</name>
   <tag></tag>
   <elementGuidId>ec3249c1-8f5a-476b-9a19-a15524e54456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li/a[normalize-space(text())='字典管理']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li/a[normalize-space(text())='字典管理']</value>
   </webElementProperties>
</WebElementEntity>
