<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>日志管理</description>
   <name>tbtn_logManage</name>
   <tag></tag>
   <elementGuidId>6d4c479d-080f-4fc2-82c3-c3bf8820741f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li/a[normalize-space(text())='日志管理']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li/a[normalize-space(text())='日志管理']</value>
   </webElementProperties>
</WebElementEntity>
