<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>角色管理</description>
   <name>tbtn_roleManage</name>
   <tag></tag>
   <elementGuidId>80a19a57-a9df-406f-a6c6-5987e4379f1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li/a[normalize-space(text())='角色管理']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li/a[normalize-space(text())='角色管理']</value>
   </webElementProperties>
</WebElementEntity>
