<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>退出登录</description>
   <name>tbtn_logout</name>
   <tag></tag>
   <elementGuidId>d70d5d55-80ce-41e1-9c20-12d1e6c24944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[normalize-space(.)='退出登录']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[normalize-space(.)='退出登录']</value>
   </webElementProperties>
</WebElementEntity>
