<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>系统管理菜单</description>
   <name>tbtn_systemManage</name>
   <tag></tag>
   <elementGuidId>bb3eadab-9c1a-471e-9d83-86194b47a8cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[normalize-space(text())='系统管理']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[normalize-space(text())='系统管理']</value>
   </webElementProperties>
</WebElementEntity>
