<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>选择部门确认按钮</description>
   <name>btn_okPost</name>
   <tag></tag>
   <elementGuidId>de1016a8-4cc0-42be-a1bf-cbeee12c374f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@class='layui-layer-btn0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@class='layui-layer-btn0']</value>
   </webElementProperties>
</WebElementEntity>
